name: PR Workflow

on:
  push:
    branches:
    - Automation-Woocommerce

jobs:
  run_bvt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run bvt suite if PR approved
      run: |
        .github/run-tests
